# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:stat.* OR cat:physics.* OR cat:math.* OR cat:nlin.* OR cat:q-fin.* OR cat:eess.* OR cat:econ.*'

# 検索キーワード
keywords:
        SPRT: 10
        sequential probability hypothesis test: 10
        sequential probability hypothesis testing: 10
        sequential hypothesis testing: 10
        sequential hypothesis test: 10
        active hypothesis testing: 3
        active hypothesis test: 3
        hypothesis test: 3
        hypothesis testing: 3
        density ratio estimation: 10
        density estimation: 3
        early classification: 10
        early time series classification: 10
        early detection: 10
        early text classification: 10
        early text categorization: 10
        early gesture: 10
        early depression: 10
        early exit: 10
        early exiting: 10
        overthinking: 10
        reject option: 5
        reject options: 5
        reject-option: 5
        with rejection: 5
        abstain: 5
        abstaining: 5
        abstention: 5
        selective classification: 5
        few-shot: 1
        class imbalance: 3
        class-imbalance: 3
        long-tail: 3
        long tail: 3
        face recognition: 2
        metric learning: 2
        large margin: 1
        time series: 1
        time-series: 1
        time series classification: 1
        time-series classification: 1
        text classification: 1
        phase: 1
        early: 2
        earlier: 2
        earliest: 2
        earliness: 2
        catastrophic forgetting: 2
        continual: 1
        lifelong: 1
        incremental: 1
        changepoint: 3
        change-point: 3
        change point: 3

# 通知の閾値
score_threshold: 3
